services:
  mysql:
    container_name: mysql-PSL
    image: mysql:latest
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Othmane-2001
      MYSQL_DATABASE: PSL
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-PSL
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  bsl-api:
    container_name: psl-api
    image : psl/psl:1.0.0
    ports:
      - 8080:8080
    networks:
      - spring-demo
    depends_on:
      - mysql

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local
  keycloak:
    driver: local
