
FROM maven:3.8.7-openjdk-18 AS build
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests


# Runtime stage
FROM amazoncorretto:17
ARG PROFILE=dev
ARG APP_VERSION=1.0.0

WORKDIR /app
COPY --from=build /build/target/PSL-*.jar /app/

EXPOSE 8080

ENV DB_URL=jdbc:mysql://mysql-PSL:3306/PSL
ENV MAILDEV_URL=localhost
ENV ACTIVE_PROFILE=${profile}
ENV JAR_VERSION = ${APP_VERSION}

CMD java -jar -Dspring.profiles.active=${ACTIVE_PROFILE} -Dspring.datasource.url=${DB_URL}  PSL-${JAR_VERSION}.jar



